build.gradle, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/internal/ExoHelper.java
=> AOMSDK-1133 Exoplayer update

src/main/java/com/aol/mobile/sdk/renderer/internal/ExoHelper.java, src/main/java/com/aol/mobile/sdk/renderer/internal/OneExoPlayer.java
=> AOMSDK-1136 Renderer refactoring

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, .travis.yml, README.md
=> Travis CI settings

build.gradle
[YouTrack issue](https://vidible.myjetbrains.com/youtrack/issue/AOMSDK-1160)
=> Build.gradle update for CD

src/main/java/com/aol/mobile/sdk/renderer/internal/ExoHelper.java
Cross protocol redirection fix
=> AOMSDK-1174 Investigate 'Baby's First Taste Of Chocolate' video problem

src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> AOMSDK-1191 Incorrect broken trackers are fired after playAtIndex

build.gradle
=> AOMSDK-1193 Update Exoplayer to 2.4.1

src/main/java/com/aol/mobile/sdk/renderer/ExoFishEyeRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ExoSphereRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ThreeSixtyRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/VideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/sensor/CameraOrientationModule.java, src/main/java/com/aol/mobile/sdk/renderer/sensor/CameraOrientationSensor.java, src/main/java/com/aol/mobile/sdk/renderer/utils/AngleHelper.java, src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java, src/test/java/com/aol/mobile/sdk/renderer/sensor/CameraOrientationModuleTest.java
[YouTrack issue](https://vidible.myjetbrains.com/youtrack/issue/AOMSDK-1199)
=> Orientation sensor moved to stock renderer

src/main/java/com/aol/mobile/sdk/renderer/internal/ExoHelper.java, src/main/java/com/aol/mobile/sdk/renderer/internal/OneExoPlayer.java
=> AOMSDK-1205 Long video buffering on mobile internet

src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> AOMSDK-1207 Crash after ad

.travis.yml, build.gradle
=> Bintray migration

build.gradle
=> OMSDK-51 Update exoplayer to version 2.4.4

src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> OMSDK-93 Update playback duration for live video

src/main/java/com/aol/mobile/sdk/renderer/RenderersRegistry.java
=> Extra renderer check

.github/PULL_REQUEST_TEMPLATE.md, build.gradle, src/main/java/com/aol/mobile/sdk/renderer/AudioTrack.java, src/main/java/com/aol/mobile/sdk/renderer/CcTrack.java, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ThreeSixtyRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/Track.java, src/main/java/com/aol/mobile/sdk/renderer/VideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-196)
=> Pipeline for track changing

src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-113)
=> Added automatic seeking to live edge for live videos

src/main/java/com/aol/mobile/sdk/renderer/AudioTrack.java, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-229)
=> Group audio tracks by language considering id

build.gradle, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> Update exoplayer to version 2.5.2

src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> ProtocolException: unexpected end of stream

build.gradle
@OlegKozhemiakin @YaroslavKryvko Ready for review.
[JIRA](https://jira.ops.aol.com/browse/OMSDK-297)
=> Kotlin support added

.gitmodules, .travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
[JIRA](https://jira.ops.aol.com/browse/OMSDK-344)
=> Support for snapshots build

src/main/java/com/aol/mobile/sdk/renderer/CastRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
=> OMSDK-302 Chromecast implementation

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Android gradle plugin update to 3.0.0

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> Application is crashed when I try to play restricted video

renderer/src/main/java/com/aol/mobile/sdk/renderer/RenderersRegistry.java
=> Prevent warning in RenderersRegistry

.travis.yml, build.gradle, renderer/build.gradle
=> Update to 27th platform API

renderer/build.gradle
=> Update assertj-core to 3.3.0

.travis.yml, build.gradle, renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> Travis update

renderer/build.gradle
=> support-annotations fix

.travis.yml, renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/RenderersRegistry.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/VideoRenderer.java
=> Naming update

renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/CastVideoVMTranslator.java
=> castVM fix

renderer/src/main/java/com/aol/mobile/sdk/renderer/TextTrack.java
=> Subtitles telemetry

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java
=> Stop casting logic

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java
=> Add empty video listener

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java
=> Stop casting

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java
=> Delete empty video listener

renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
=> ExoPlayer version bump to 2.6.1

build.gradle, renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFishEyeRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoSphereRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/RenderersRegistry.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/FishEyeRendererProducer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/FlatRendererProducer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/ThreeSixtyRendererProducer.java
@YaroslavKryvko @OlegKozhemiakin Please, have a look
=> Public API tracking integration

LICENSE.md
@OlegKozhemiakin @YaroslavKryvko Please, have a look
=> MIT license

.gitignore
@YaroslavKryvko @OlegKozhemiakin Please, review
=> Ignore proguard-classes.pro

renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
@OlegKozhemiakin @YaroslavKryvko Please, review
=> ExoPlayer update to 2.7.1

renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
@YaroslavKryvko @OlegKozhemiakin Please, review
=> Subtitle rendering using ExoPlayer ui module

renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-776)
=> Refactored Chromecast module usage

renderer/build.gradle
@YaroslavKryvko @OlegKozhemiakin Please, review
=> Fix API changes generation bug

renderer/build.gradle
=> Updated chromecast version

renderer/build.gradle
=> Renderer gradle fix

build.gradle, renderer/build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ThreeSixtyRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/gles/FishEyeSphere.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/gles/SceneRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/sensor/CameraOrientationSensor.java
Latest versions distribution chart can be found [here](https://developer.android.com/about/dashboards/)
@OlegKozhemiakin @YaroslavKryvko  Please, review.
[JIRA](https://jira.ops.aol.com/browse/OMSDK-1546)
=> Bump minimal Android version to 19

.travis.yml, build.gradle, gradle.properties, renderer/build.gradle
=> Android min API version downgrade to 16

build.gradle, renderer/src/main/java/com/aol/mobile/sdk/renderer/AudioTrack.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFishEyeRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoFlatRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoSphereRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/RenderersRegistry.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ThreeSixtyRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/FishEyeRendererProducer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/FlatRendererProducer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/producer/ThreeSixtyRendererProducer.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-1926)
=> Update ExoPlayer to 2.8.4

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-2030)
=> Upscale fix

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExternalSubtitle.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/TextTrack.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
* Added ExternalSubtitle to VideoVM
* Merge external subtitles with internal
[JIRA](https://jira.ops.aol.com/browse/OMSDK-2007)
=> Unify way of rendering external and internal subs inside of video renderer

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-2064)
=> Proper language title in CC list

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlDecoder.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlNode.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlRegion.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlRenderUtil.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlStyle.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlSubtitle.java
[JIRA](https://jira.ops.aol.com/browse/OMSDK-2071)
=> Custom ttml decoder, that makes hours timing optional

.github/PULL_REQUEST_TEMPLATE.md, gradle/wrapper/gradle-wrapper.properties, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
@VerizonAdPlatforms/mobile-sdk-developers : Ready for review.
[JIRA](https://jira.ouroath.com/browse/VSDK-4626)
=> Implement switch for embedded cc style

.travis.yml, build.gradle
[JIRA](https://jira.ouroath.com/browse/VSDK-XXXX)
=> Fixed build

gradle/wrapper/gradle-wrapper.properties
[JIRA](https://jira.ouroath.com/browse/VSDK-XXXX)
=> another build fix

.travis.yml, renderer/build.gradle
[JIRA](https://jira.ouroath.com/browse/VSDK-XXXX)
=> specify compileSdkVersion

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/TextTrack.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/internal/ttml/TtmlDecoder.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[JIRA](https://jira.ouroath.com/browse/VSDK-4715)
=> SDK should ignore the subtitle format if we can’t parse it

.travis.yml, build.gradle, renderer/build.gradle
=> Gradle android plugin downgrade

renderer/build.gradle
@OlegKozhemiakin Please, review
=> Fix artifacts publishing

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java
@OlegKozhemiakin Please, review
[JIRA](https://jira.ouroath.com/browse/VSDK-5018)
=> Initial bitrate added (~1.5 Mbytes/s)

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[JIRA](https://jira.ouroath.com/browse/VSDK-5025)
=> Mitigate playback issues on low-end Amazon Fire TV devices

renderer/src/main/java/com/aol/mobile/sdk/renderer/ErrorInfo.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[VSDK-5169](https://jira.ouroath.com/browse/VSDK-5169)
=> expose playback error info

renderer/src/main/java/com/aol/mobile/sdk/renderer/ExoVideoRenderer.java, renderer/src/main/java/com/aol/mobile/sdk/renderer/viewmodel/VideoVM.java
[JIRA](https://jira.ouroath.com/browse/VSDK-5351)
=> add retry ability to recover from error state
